# fly.toml app configuration file generated for titanic-survival-prediction on 2025-07-29T21:02:49-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'app'
primary_region = 'gru'

[build]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  protocol = "tcp"
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '30s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4

