# fly.toml app configuration file generated for titanic-survival-amon on 2025-07-29T14:51:17-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'titanic-survival-amon'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true # 'true' é o valor mais comum aqui
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '15s'
    method = 'GET'
    path = '/_stcore/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1