# fly.toml app configuration file generated for titanic-survival-prediction on 2025-07-29T17:58:35-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'titanic-survival-prediction'
primary_region = 'gru'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '15s'
    method = 'GET'
    path = '/_stcore/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
