app = "titanic-survival-prediction"
primary_region = "gru"  # Use a região mais próxima (pode ser "gru" para São Paulo)

[build]
  dockerfile = "Dockerfile"
  
[env]
  DJANGO_SETTINGS_MODULE = "titanic_project.settings"
  PYTHONUNBUFFERED = "1"

[deploy]
  release_command = "python manage.py migrate"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
