name: AWS Check - Push Image to ECR via OIDC

on:
  workflow_dispatch:  # manual trigger from GitHub Actions tab
  push:
    branches: ["main"]  # optional: run automatically on main pushes

permissions:
  id-token: write       # required for OIDC federation
  contents: read
  packages: read        # allows pulling from GHCR

jobs:
  push-to-ecr:
    name: Push Docker Image to AWS ECR
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Login to GHCR to pull the image built by CI
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      # 3️⃣ Pull image from GHCR
      - name: Pull image from GHCR
        run: docker pull ghcr.io/amonvix/titanic:${{ github.sha }}

      # 4️⃣ Configure AWS credentials using OIDC
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      # 5️⃣ Retrieve AWS account ID dynamically
      - id: aws_account
        run: echo "id=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_OUTPUT

      # 6️⃣ Authenticate Docker to ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region "${{ vars.AWS_REGION }}" \
            | docker login --username AWS --password-stdin \
              "${{ steps.aws_account.outputs.id }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com"

      # 7️⃣ Build tag for ECR and push image
      - name: Push image to ECR
        env:
          AWS_ACCOUNT_ID: ${{ steps.aws_account.outputs.id }}
          ECR_REPO: ${{ vars.AWS_ECR_REPO }}
          REGION: ${{ vars.AWS_REGION }}
        run: |
          IMAGE_ECR="${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${ECR_REPO}:${GITHUB_SHA}"
          echo "📦 Building tag: $IMAGE_ECR"
          docker tag ${{ vars.GHCR_IMAGE }}:${{ github.sha }} "$IMAGE_ECR"
          docker push "$IMAGE_ECR"

      # 8️⃣ Output summary
      - name: Summary
        run: |
          echo "✅ Image successfully pushed to ECR"
          echo "🪪 Account: ${{ steps.aws_account.outputs.id }}"
          echo "🪣 Repo: ${{ vars.AWS_ECR_REPO }}"
          echo "🌍 Region: ${{ vars.AWS_REGION }}"
